"use client";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/context/AuthContext";
import { WebSocketContextProvider } from "@/context/WebSocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <time dateTime="2023-08-02" suppressHydrationWarning />
        <AuthContextProvider>
          <WebSocketContextProvider>{children}</WebSocketContextProvider>
        </AuthContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
